'use client';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { recordsApi } from '@/lib/api';
import { EmptyState, ErrorState, Skeleton } from '@/components/shared';
export default function Page() {
  const [month,setMonth]=useState(new Date().toISOString().slice(0,7)); const query=useQuery({queryKey:['attendance',month],queryFn:()=>recordsApi('/hr/attendance').list({limit:'500'})});
  const days=useMemo(()=>{const [year,mon]=month.split('-').map(Number); return Array.from({length:new Date(year,mon,0).getDate()},(_,i)=>i+1)},[month]); const rows=(query.data?.data||[]) as Record<string,unknown>[];
  if(query.isPending)return <Skeleton className="h-72"/>; if(query.isError)return <ErrorState message={query.error.message} retry={()=>query.refetch()}/>;
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Attendance Calendar</h1><p className="text-sm text-slate-500">Employee attendance by day, loaded from the API.</p></div><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-lg border px-3 py-2"/></div>{rows.length===0?<EmptyState title="No attendance records" description="Mark attendance records to populate the calendar."/>:<div className="overflow-x-auto rounded-xl border bg-white"><table className="min-w-[900px] w-full text-left text-sm"><thead className="border-b bg-slate-50"><tr><th className="sticky left-0 bg-slate-50 p-3">Employee</th>{days.map(day=><th key={day} className="p-2 text-center">{day}</th>)}</tr></thead><tbody>{Array.from(new Set(rows.map(row=>String(row.employee_id)))).map(employee=><tr key={employee} className="border-b"><td className="sticky left-0 bg-white p-3 font-medium">{employee}</td>{days.map(day=>{const date=`${month}-${String(day).padStart(2,'0')}`;const record=rows.find(row=>String(row.employee_id)===employee&&String(row.attendance_date).startsWith(date));return <td key={day} className="p-2 text-center">{record?<span className={`inline-flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${record.status==='present'?'bg-emerald-100 text-emerald-700':record.status==='absent'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{String(record.status).slice(0,1).toUpperCase()}</span>:'-'}</td>})}</tr>)}</tbody></table></div>}</div>;
}
