'use client';
import { ModuleWorkspace } from '@/components/module-workspace';
import { MasterSelect } from '@/components/master-select';
import { WorkflowAction } from '@/components/workflow-action';
import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Plus, Trash2 } from 'lucide-react';
import { workflowApi } from '@/lib/api';
import { Field, WorkflowCard, inputClass } from '@/components/workflow-card';
export default function Page() {
  const [bomId, setBomId] = useState(''); const [rows, setRows] = useState([{ item_id:'', quantity:'1', scrap_percent:'0', rate:'0' }]);
  const mutation = useMutation({ mutationFn: () => workflowApi.saveBomComponents(bomId, rows.map(row => ({ ...row, quantity:Number(row.quantity), scrap_percent:Number(row.scrap_percent), rate:Number(row.rate) }))) });
  return <div className="space-y-6"><ModuleWorkspace title="Bills of Materials" description="Maintain versioned manufacturing recipes." endpoint="/production/bom" actionEndpoint="/production/bom" statusOptions={['active','archived']} columns={['bom_code','finished_item_id','output_qty','version_no','is_active']} fields={[{key:'bom_code',label:'BOM code',required:true},{key:'finished_item_id',label:'Finished item',required:true},{key:'output_qty',label:'Output quantity',type:'number',required:true}]} /><WorkflowAction title="Create BOM version" endpoint="/production/bom/{bom_id}/versions" fields={[{key:'bom_id',label:'Source BOM',required:true},{key:'bom_code',label:'New version code',required:true}]} /><WorkflowCard title="Bill of Materials Builder" description="Save a BOM's component structure with quantity, scrap and costing details."><div className="mb-5 max-w-md"><Field label="BOM ID"><MasterSelect field="bom_id" required className={inputClass} value={bomId} onChange={setBomId} /></Field></div><div className="space-y-3">{rows.map((row,index) => <div key={index} className="grid items-end gap-3 rounded-lg border p-3 md:grid-cols-5"><Field label="Item ID"><MasterSelect field="item_id" required className={inputClass} value={row.item_id} onChange={value => setRows(rows.map((r,i)=>i===index?{...r,item_id:value}:r))} /></Field><Field label="Quantity"><input required type="number" min="0.001" className={inputClass} value={row.quantity} onChange={e => setRows(rows.map((r,i)=>i===index?{...r,quantity:e.target.value}:r))} /></Field><Field label="Scrap %"><input type="number" className={inputClass} value={row.scrap_percent} onChange={e => setRows(rows.map((r,i)=>i===index?{...r,scrap_percent:e.target.value}:r))} /></Field><Field label="Rate"><input type="number" className={inputClass} value={row.rate} onChange={e => setRows(rows.map((r,i)=>i===index?{...r,rate:e.target.value}:r))} /></Field><button type="button" disabled={rows.length===1} onClick={() => setRows(rows.filter((_,i)=>i!==index))} className="rounded-lg border p-2 text-red-600 disabled:opacity-40"><Trash2 size={17} /></button></div>)}</div><div className="mt-5 flex gap-2"><button type="button" onClick={() => setRows([...rows,{item_id:'',quantity:'1',scrap_percent:'0',rate:'0'}])} className="rounded-lg border px-4 py-2"><Plus size={16} className="mr-2 inline" />Add component</button><button type="button" disabled={mutation.isPending} onClick={() => mutation.mutate()} className="rounded-lg bg-indigo-600 px-4 py-2 text-white">{mutation.isPending?'Saving...':'Save components'}</button></div>{mutation.isSuccess && <p className="mt-4 text-sm text-emerald-700">BOM components saved.</p>}{mutation.isError && <p className="mt-4 text-sm text-red-600">{mutation.error.message}</p>}</WorkflowCard></div>;
}
