'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { authApi, publicApi } from '@/lib/api';
import { useQuery } from '@tanstack/react-query';
export default function RegisterPage() {
  const router = useRouter(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [selectedModules, setSelectedModules] = useState<string[]>([]);
  const modules = useQuery({ queryKey: ['public-modules'], queryFn: () => publicApi.modules() });
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); const data = { company_name: String(form.get('company_name') || ''), owner_name: String(form.get('owner_name') || ''), owner_email: String(form.get('owner_email') || ''), password: String(form.get('password') || ''), subdomain: String(form.get('subdomain') || ''), plan: String(form.get('plan') || 'starter'), duration_months: Number(form.get('duration_months') || 1), modules: selectedModules }; try { const result = await authApi.register(data); router.push(`/onboarding?organization_id=${result.data.organization_id}&subscription_id=${result.data.subscription_id}&hostname=${encodeURIComponent(result.data.hostname)}`); } catch (e) { setError(e instanceof Error ? e.message : 'Registration failed'); } finally { setBusy(false); } }
  const availableModules = (modules.data?.data || []).filter(module => module.pricing?.length && module.is_purchasable !== false);
  return <main className="flex min-h-screen items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-xl border bg-white p-8 shadow-sm"><h1 className="text-2xl font-bold">Create organization</h1><p className="text-sm text-slate-500">Your workspace will remain pending until payment is verified.</p>{error && <div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<input required name="company_name" placeholder="Company name" className="w-full rounded-lg border p-3" /><input required name="subdomain" placeholder="Subdomain, e.g. abc" className="w-full rounded-lg border p-3" /><input name="owner_name" placeholder="Owner name" className="w-full rounded-lg border p-3" /><input required type="email" name="owner_email" placeholder="Owner email" className="w-full rounded-lg border p-3" /><input required type="password" name="password" placeholder="Password" className="w-full rounded-lg border p-3" /><div className="grid grid-cols-2 gap-3"><select name="plan" className="rounded-lg border p-3"><option value="starter">Starter</option><option value="growth">Growth</option><option value="pro">Professional</option></select><select name="duration_months" className="rounded-lg border p-3"><option value="1">Monthly</option><option value="12">Yearly</option></select></div><div className="rounded-lg border p-3"><p className="mb-2 text-sm font-semibold">Select modules</p><div className="grid gap-2 sm:grid-cols-2">{availableModules.filter(module => module.key !== 'dashboard' && module.active !== false).map(module => <label key={module.key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selectedModules.includes(module.key)} onChange={event => setSelectedModules(current => event.target.checked ? [...current, module.key] : current.filter(key => key !== module.key))} />{module.name}</label>)}</div></div><button disabled={busy} className="w-full rounded-lg bg-primary p-3 font-semibold text-white">{busy ? 'Creating...' : 'Continue to payment'}</button><a className="block text-center text-sm text-primary" href="/login">Back to sign in</a></form></main>;
}
