'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, CheckCheck } from 'lucide-react';
import { orgApi, workflowApi } from '@/lib/api';
import { EmptyState, ErrorState, Skeleton } from '@/components/shared';
export default function Page() {
  const client=useQueryClient(); const query=useQuery({queryKey:['alerts'],queryFn:orgApi.alerts}); const read=useMutation({mutationFn:(id:string)=>workflowApi.markNotificationRead(id),onSuccess:()=>client.invalidateQueries({queryKey:['alerts']})}); const readAll=useMutation({mutationFn:workflowApi.markAllNotificationsRead,onSuccess:()=>client.invalidateQueries({queryKey:['alerts']})});
  if(query.isPending)return <Skeleton className="h-64"/>; if(query.isError)return <ErrorState message={query.error.message} retry={()=>query.refetch()}/>; const rows=query.data.data||[];
  return <div className="space-y-5"><div className="flex items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Notifications</h1><p className="text-sm text-slate-500">Operational alerts from the connected ERP workspace.</p></div><button onClick={()=>readAll.mutate()} disabled={readAll.isPending||!rows.length} className="rounded-lg border px-4 py-2 text-sm disabled:opacity-40"><CheckCheck size={16} className="mr-2 inline"/>Mark all read</button></div>{!rows.length?<EmptyState title="No notifications" description="New alerts will appear here."/>:<div className="space-y-3">{rows.map(item=><article key={item.id} className={`rounded-xl border bg-white p-4 ${item.is_read?'opacity-60':'border-indigo-200'}`}><div className="flex gap-3"><Bell className="mt-1 text-indigo-600" size={18}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{item.title}</h2>{!item.is_read&&<button onClick={()=>read.mutate(item.id)} className="text-xs text-indigo-600">Mark read</button>}</div><p className="mt-1 text-sm text-slate-600">{item.description||'No additional details.'}</p><p className="mt-2 text-xs text-slate-400">{item.severity} · {item.created_at}</p></div></div></article>)}</div>}</div>;
}
