'use client';
import { useMemo, useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Plus, Trash2 } from 'lucide-react';
import { workflowApi } from '@/lib/api';
import { Field, WorkflowCard, inputClass } from '@/components/workflow-card';
export default function Page() {
  const [invoiceId,setInvoiceId]=useState(''); const [orgState,setOrgState]=useState(''); const [customerState,setCustomerState]=useState(''); const [lines,setLines]=useState([{item_id:'',description:'',quantity:'1',rate:'0',discount_percent:'0',gst_rate:'18'}]);
  const totals=useMemo(()=>lines.reduce((sum,line)=>{const taxable=Number(line.quantity)*Number(line.rate)*(1-Number(line.discount_percent)/100); const tax=taxable*Number(line.gst_rate)/100; return {taxable:sum.taxable+taxable,tax:sum.tax+tax,total:sum.total+taxable+tax};},{taxable:0,tax:0,total:0}),[lines]);
  const mutation=useMutation({mutationFn:()=>workflowApi.saveInvoiceLines(invoiceId,{org_state:orgState,customer_state:customerState,items:lines.map(line=>({...line,quantity:Number(line.quantity),rate:Number(line.rate),discount_percent:Number(line.discount_percent),gst_rate:Number(line.gst_rate)}))})});
  return <WorkflowCard title="GST Invoice Builder" description="Build invoice line items and persist calculated taxable value and GST splits."><div className="grid gap-4 md:grid-cols-3"><Field label="Invoice ID"><input required className={inputClass} value={invoiceId} onChange={e=>setInvoiceId(e.target.value)} /></Field><Field label="Organization state"><input required className={inputClass} value={orgState} onChange={e=>setOrgState(e.target.value)} /></Field><Field label="Customer state"><input required className={inputClass} value={customerState} onChange={e=>setCustomerState(e.target.value)} /></Field></div><div className="mt-5 space-y-3">{lines.map((line,index)=><div key={index} className="grid gap-3 rounded-lg border p-3 md:grid-cols-7"><Field label="Item"><input className={inputClass} value={line.item_id} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,item_id:e.target.value}:l))}/></Field><Field label="Description"><input className={inputClass} value={line.description} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,description:e.target.value}:l))}/></Field><Field label="Qty"><input type="number" min="0.001" className={inputClass} value={line.quantity} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,quantity:e.target.value}:l))}/></Field><Field label="Rate"><input type="number" min="0" className={inputClass} value={line.rate} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,rate:e.target.value}:l))}/></Field><Field label="Disc %"><input type="number" className={inputClass} value={line.discount_percent} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,discount_percent:e.target.value}:l))}/></Field><Field label="GST %"><input type="number" className={inputClass} value={line.gst_rate} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,gst_rate:e.target.value}:l))}/></Field><button type="button" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,i)=>i!==index))} className="rounded-lg border p-2 text-red-600 disabled:opacity-40"><Trash2 size={17}/></button></div>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={()=>setLines([...lines,{item_id:'',description:'',quantity:'1',rate:'0',discount_percent:'0',gst_rate:'18'}])} className="rounded-lg border px-4 py-2"><Plus size={16} className="mr-2 inline"/>Add line</button><div className="text-right text-sm"><p>Taxable: ₹{totals.taxable.toFixed(2)}</p><p>GST: ₹{totals.tax.toFixed(2)}</p><p className="text-lg font-bold">Total: ₹{totals.total.toFixed(2)}</p></div><button type="button" disabled={mutation.isPending} onClick={()=>mutation.mutate()} className="rounded-lg bg-indigo-600 px-4 py-2 text-white">{mutation.isPending?'Saving...':'Save invoice lines'}</button></div>{mutation.isSuccess&&<p className="mt-4 text-sm text-emerald-700">Invoice lines saved.</p>}{mutation.isError&&<p className="mt-4 text-sm text-red-600">{mutation.error.message}</p>}</WorkflowCard>;
}
